-- vim.g.loaded_netrw = 1
-- vim.g.loaded_netrwPlugin = 1
--
-- return {
--   {
--     'nvim-tree/nvim-tree.lua',
--     config = function()
--       require('nvim-tree').setup {
--         sort = {
--           sorter = 'case_sensitive',
--         },
--         view = {
--           width = 50,
--         },
--         renderer = {
--           group_empty = true,
--         },
--         filters = {
--           dotfiles = false,
--         },
--       }
--
--       vim.keymap.set('n', '<leader>f', vim.cmd.NvimTreeToggle, { desc = 'NvimTreeToggle' })
--     end,
--   },
-- }

return {}
