[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

# [shell]
# program = "/bin/zsh"
# args = [
#   "--login",
#   "-c",
#   "{ tmux ls 2>/dev/null || echo \"default: create new session\"; } | fzf --print-query | tail -n 1 | sed -e \"s/:.*\\$//\" | read session_name && tmux attach-session -t $session_name 2>/dev/null || tmux new -s $session_name",
# ]

[window]
resize_increments = true
option_as_alt = "Both"
# startup_mode = "Maximized"
# opacity = 0.64
# blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 14

[env]
TERM = "xterm-256color"

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },
  { key = "ArrowRight", mods = "Option", chars = "\u001bf" },
  { key = "ArrowLeft", mods = "Command", chars = "\u0001" },
  { key = "ArrowRight", mods = "Command", chars = "\u0005" },
  { key = "Slash", mods = "Control", chars = "\u001f" },
  { key = "NumpadSubtract", chars = "-" },
  # macOS
  { key = "T", mods = "Command", action = "ReceiveChar" },
]


# neutralized dracula
[colors.primary]

background = "#2b2b2b"        # 282a36
foreground = "#cccccc"        # f8f8f2
bright_foreground = "#ffffff"

[colors.cursor]

text = "#2b2b2b"   # 282a36
cursor = "#cccccc" # f8f8f2

[colors.vi_mode_cursor]

text = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text = "CellForeground"
background = "#484848"  # 44475a

[colors.normal]

black = "#232323"   # 21222c
red = "#ff5555"
green = "#50fa7b"
yellow = "#f1fa8c"
blue = "#bd93f9"
magenta = "#ff79c6"
cyan = "#8be9fd"
white = "#cccccc"   # f8f8f2

[colors.bright]

black = "#747474"   # 6272a4
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.search.matches]

foreground = "#484848" # 44475a
background = "#50fa7b"

[colors.search.focused_match]

foreground = "#484848" # 44475a
background = "#ffb86c" # ffb86c

[colors.footer_bar]

background = "#2b2b2b" # 282a36
foreground = "#cccccc" # f8f8f2

[colors.hints.start]

foreground = "#2b2b2b" # 282a36
background = "#f1fa8c"

[colors.hints.end]

foreground = "#f1fa8c"
background = "#2b2b2b" # 282a36
